import { useState } from "react";
import TwoWheelerShowcase from "./TwoWheelerShowcase";

// Sample data based on the schema and examples
const sampleTwoWheelers = [
  {
    id: "TW-001",
    brand: "Yamaha",
    model: "FZ-S V3",
    manufacturingYear: 2021,
    engineCapacityCC: 149,
    transmissionType: "Manual",
    driveType: "Chain",
    fuelType: "Petrol",
    fuelTankCapacityLiters: 12,
    mileageKMPL: 45,
    topSpeedKMPH: 120,
    powerHP: 13.2,
    torqueNm: 13.3,
    emissionStandard: "BS6",
    dimensions: {
      lengthMm: 1990,
      widthMm: 785,
      heightMm: 1035,
    },
    wheelBaseMm: 1325,
    groundClearanceMm: 160,
    weightKg: 135,
    seatingCapacity: 2,
    colorOptions: ["Matte Black", "Metallic Blue", "Red"],
    wheelType: "Alloy",
    tireSize: {
      front: "100/80-17",
      rear: "140/60-17",
    },
    brakes: {
      front: "Disc",
      rear: "Disc",
    },
    abs: true,
    features: ["LED Headlamp", "Digital Console", "Slipper Clutch"],
    warrantyYears: 3,
    price: 109000,
  },
  {
    id: "TW-002",
    brand: "Honda",
    model: "Activa 6G",
    manufacturingYear: 2022,
    engineCapacityCC: 109,
    transmissionType: "Automatic",
    driveType: "Belt",
    fuelType: "Petrol",
    fuelTankCapacityLiters: 5.3,
    mileageKMPL: 56,
    topSpeedKMPH: 90,
    powerHP: 7.68,
    torqueNm: 8.79,
    emissionStandard: "BS6",
    dimensions: {
      lengthMm: 1772,
      widthMm: 702,
      heightMm: 1136,
    },
    wheelBaseMm: 1264,
    groundClearanceMm: 158,
    weightKg: 107,
    seatingCapacity: 2,
    colorOptions: ["Pearl White", "Matte Axis Grey", "Rebel Red"],
    wheelType: "Spoke",
    tireSize: {
      front: "90/90-12",
      rear: "90/100-10",
    },
    brakes: {
      front: "Drum",
      rear: "Drum",
    },
    abs: false,
    features: ["External Fuel Filler", "Mobile Charging Socket"],
    warrantyYears: 2,
    price: 74500,
  },
  {
    id: "TW-003",
    brand: "Royal Enfield",
    model: "Classic 350",
    manufacturingYear: 2023,
    engineCapacityCC: 349,
    transmissionType: "Manual",
    driveType: "Chain",
    fuelType: "Petrol",
    fuelTankCapacityLiters: 13,
    mileageKMPL: 32,
    topSpeedKMPH: 115,
    powerHP: 20.2,
    torqueNm: 27,
    emissionStandard: "BS6",
    dimensions: {
      lengthMm: 2145,
      widthMm: 785,
      heightMm: 1090,
    },
    wheelBaseMm: 1390,
    groundClearanceMm: 170,
    weightKg: 195,
    seatingCapacity: 2,
    colorOptions: [
      "Chrome Bronze",
      "Signals Marsh Grey",
      "Gunmetal Grey",
      "Stealth Black",
    ],
    wheelType: "Spoke",
    tireSize: {
      front: "100/90-19",
      rear: "120/80-18",
    },
    brakes: {
      front: "Disc",
      rear: "Disc",
    },
    abs: true,
    features: [
      "Tripper Navigation",
      "Dual-Channel ABS",
      "Semi-Digital Console",
    ],
    warrantyYears: 3,
    price: 195000,
  },
  {
    id: "TW-004",
    brand: "TVS",
    model: "iQube Electric",
    manufacturingYear: 2023,
    engineCapacityCC: 0,
    transmissionType: "Automatic",
    driveType: "Belt",
    fuelType: "Electric",
    fuelTankCapacityLiters: 0,
    mileageKMPL: 0,
    topSpeedKMPH: 78,
    powerHP: 5.9,
    torqueNm: 140,
    emissionStandard: "Zero Emission",
    dimensions: {
      lengthMm: 1800,
      widthMm: 645,
      heightMm: 1140,
    },
    wheelBaseMm: 1255,
    groundClearanceMm: 150,
    weightKg: 118,
    seatingCapacity: 2,
    colorOptions: ["White", "Titanium Grey"],
    wheelType: "Alloy",
    tireSize: {
      front: "90/90-12",
      rear: "90/90-12",
    },
    brakes: {
      front: "Disc",
      rear: "Drum",
    },
    abs: false,
    features: [
      "Smart Connect",
      "LED Lighting",
      "TFT Display",
      "Regenerative Braking",
    ],
    warrantyYears: 3,
    price: 124000,
  },
  {
    id: "TW-005",
    brand: "Bajaj",
    model: "Pulsar N160",
    manufacturingYear: 2022,
    engineCapacityCC: 160,
    transmissionType: "Manual",
    driveType: "Chain",
    fuelType: "Petrol",
    fuelTankCapacityLiters: 14,
    mileageKMPL: 42,
    topSpeedKMPH: 110,
    powerHP: 15.9,
    torqueNm: 14.6,
    emissionStandard: "BS6",
    dimensions: {
      lengthMm: 2017,
      widthMm: 804,
      heightMm: 1062,
    },
    wheelBaseMm: 1353,
    groundClearanceMm: 165,
    weightKg: 154,
    seatingCapacity: 2,
    colorOptions: ["Racing Red", "Brooklyn Black", "Caribbean Blue"],
    wheelType: "Alloy",
    tireSize: {
      front: "100/80-17",
      rear: "130/70-17",
    },
    brakes: {
      front: "Disc",
      rear: "Disc",
    },
    abs: true,
    features: ["LED Projector Headlamp", "USB Charging", "Split Seat"],
    warrantyYears: 2,
    price: 125000,
  },
  {
    id: "TW-006",
    brand: "Suzuki",
    model: "Access 125",
    manufacturingYear: 2023,
    engineCapacityCC: 124,
    transmissionType: "Automatic",
    driveType: "Belt",
    fuelType: "Petrol",
    fuelTankCapacityLiters: 5.5,
    mileageKMPL: 55,
    topSpeedKMPH: 95,
    powerHP: 8.7,
    torqueNm: 10,
    emissionStandard: "BS6",
    dimensions: {
      lengthMm: 1870,
      widthMm: 685,
      heightMm: 1160,
    },
    wheelBaseMm: 1265,
    groundClearanceMm: 160,
    weightKg: 104,
    seatingCapacity: 2,
    colorOptions: [
      "Pearl Mirage White",
      "Metallic Matte Bordeaux Red",
      "Glass Sparkle Black",
    ],
    wheelType: "Alloy",
    tireSize: {
      front: "90/90-12",
      rear: "90/100-10",
    },
    brakes: {
      front: "Disc",
      rear: "Drum",
    },
    abs: false,
    features: ["LED Position Lamp", "Chrome Garnish", "USB Charger"],
    warrantyYears: 2,
    price: 84000,
  },
  {
    id: "TW-007",
    brand: "Ather",
    model: "450X",
    manufacturingYear: 2024,
    engineCapacityCC: 0,
    transmissionType: "Automatic",
    driveType: "Belt",
    fuelType: "Electric",
    mileageKMPL: 0,
    topSpeedKMPH: 90,
    powerHP: 8.38,
    torqueNm: 26,
    emissionStandard: "Zero Emission",
    dimensions: {
      lengthMm: 1837,
      widthMm: 701,
      heightMm: 1178,
    },
    wheelBaseMm: 1290,
    groundClearanceMm: 160,
    weightKg: 111,
    seatingCapacity: 2,
    colorOptions: ["Space Grey", "Mint Green", "White"],
    wheelType: "Alloy",
    tireSize: {
      front: "90/90-12",
      rear: "90/90-12",
    },
    brakes: {
      front: "Disc",
      rear: "Disc",
    },
    abs: true,
    features: [
      "7-inch Touchscreen",
      "Navigation",
      "Bluetooth Connectivity",
      "OTA Updates",
    ],
    warrantyYears: 3,
    price: 158000,
  },
];

export default function App() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-black pt-20">
      <TwoWheelerShowcase vehicles={sampleTwoWheelers} />
    </div>
  );
}
